name = "ConformalGaussHypergeometric"
uuid = "a0f86bc1-470f-4209-bc5c-9aadbf1cec0c"
authors = ["Caleb Jacobs <Caleb.Jacobs@colorado.edu>"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
